### ISSUE TITLE
Incorrect behavior when response status is not 200

### ISSUE THREAD

**Issue by automation-stack** [echocat/caddy-filter#11] opened 2017-06-11 11:32 UTC
When used any `http.filter` all `http.redir`'s or `http.status` serves with status 200 instead status from redirection rule.

**Comment by automation-stack** [comment] 2017-06-14 23:51
@blaubaer  This is very frustrating bug :(

**Comment by blaubaer** [comment] 2017-06-17 11:51
This is a duplicate of #8

**Closed as completed by blaubaer** 2017-06-17 11:51 UTC
Labels: duplicate
